name: Run Predictions

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  prediction:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy scikit-learn tensorflow

    - name: Run prediction script
      run: python prediction_script.py

    - name: Commit and push prediction.db
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add prediction.db
        git commit -m 'Add prediction.db'
        git push
