name: Train and Predict RNN Models

on:
  workflow_dispatch:
  schedule:
    - cron: '30 16 * * 1-5' # Run every 6 hours

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tensorflow pandas scikit-learn

      - name: Run training script
        run: python train_rnn.py

      - name: Commit and push trained models
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add -f models || echo "No models folder found."
          git commit -m "Add trained models and related artifacts" || echo "Nothing to commit."
          git push || echo "Nothing to push."

  predict:
    runs-on: ubuntu-latest
    needs: train
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tensorflow pandas scikit-learn

      - name: Run prediction script
        run: python predict_rnn.py

      - name: Commit and push predictions
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add predictions || echo "No predictions folder found."
          git commit -m "Add prediction results" || echo "Nothing to commit."
          git push || echo "Nothing to push."
